# Generated by Django 5.1 on 2024-09-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comments', to='core.note'),
        ),
    ]
