# Generated by Django 5.1 on 2024-09-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notecomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecomment',
            old_name='post',
            new_name='note',
        ),
    ]
