# Generated by Django 5.1 on 2024-09-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_note_profile'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notes', to='user.profile'),
        ),
    ]
