# Generated by Django 5.1 on 2024-09-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_note_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
